### ISSUE TITLE
Support the loading of a debug DLL to winfspy

### ISSUE THREAD

**Issue by vxgmichel** [Scille/winfspy#12]
This is how the winfsp DLL is loaded at the moment:

https://github.com/Scille/winfspy/blob/6cd4d27e922b9a986e67962001f7796dfbc7276c/src/winfspy/plumbing/bindings.py#L14-L17

https://github.com/Scille/winfspy/blob/6cd4d27e922b9a986e67962001f7796dfbc7276c/src/winfspy/plumbing/get_winfsp_dir.py#L18-L28

Note that `WINFSP_LIBRARY_PATH` is used three times:
- `%WINFSP_LIBRARY_PATH%/inc`: used when building the `_bindings` module
- `%WINFSP_LIBRARY_PATH%/lib`: used when building the `_bindings` module
- `%WINFSP_LIBRARY_PATH%/bin`: used to load the dll

This makes it hard to load a debug DLL without patching the source code, since the path to to the debug DLL typically looks like this:

    C:\\Users\\User\\Projects\\winfsp\\build\\VStudio\\build\\Debug

I guess there are several ways to go about it. The most obvious way would be to add a `%WINFSP_DEBUG_PATH%` that overrides `%WINFSP_LIBRARY_PATH%/bin` when it is defined. In this case, adding a warning (e.g "The debug library is being loaded") might make sense.

Thanks to @billziss-gh for the suggestion!

**Comment by billziss-gh** [comment]
>  The most obvious way would be to add a `%WINFSP_DEBUG_PATH%` that overrides `%WINFSP_LIBRARY_PATH%/bin` when it is defined. In this case, adding a warning (e.g "The debug library is being loaded") might make sense.

I think this solution would be simple and effective.

**Comment by vxgmichel** [comment]
Implemented in #14
