### ISSUE TITLE
Change in WinFSP 1.7 (from 1.7B1 to 1.7)

### ISSUE THREAD

**Issue by bitlogik** [Scille/winfspy#24]
Following [an investigation on Parsec](https://github.com/Scille/parsec-cloud/issues/1225), we have a recurring error in the test pipeline.
```
tests/core/mountpoint/test_winfstest.py::test_winfstest[10_GetSetSecurity.t] XFAIL
tests\core\mountpoint\test_winfstest.py:59

>       assert errno == getattr(winerror, expected), f"Expected {expected}, got {message}"
E       AssertionError: Expected ERROR_PATH_NOT_FOUND, got The directory name is invalid.
E       assert 267 == 3
E         -267
E         +3

expect(
    "CreateFile %s\\bar GENERIC_WRITE 0 0 CREATE_NEW FILE_ATTRIBUTE_NORMAL 0" % name,
    "ERROR_PATH_NOT_FOUND",
)

** Running command:
-> CreateFile %s\1c8ab2fd-6429-44d0-a4a1-bdf60a98cd04\bar GENERIC_WRITE 0 0 CREATE_NEW FILE_ATTRIBUTE_NORMAL 0
-> Expecting: ERROR_PATH_NOT_FOUND
-> Got: errno=267, message='The directory name is invalid.'

```
This might be a breaking change in WinFSP 1.7 (B2) :
https://github.com/billziss-gh/winfsp/commit/906633822006114a66bdb00f14a1c94a304b1785

From what we can understand, there's no more error thrown "ERROR_PATH_NOT_FOUND" (STATUS_OBJECT_NAME_NOT_FOUND = ENOENT), but the Win32 throw NotADirectoryError (WinError 267 = 'The directory name is invalid.')

Some pipelines for parsec-cloud tests passed because the "XFAIL" in winfstest may not trigger a bad test.

**Comment by bitlogik** [comment]
As stated [in the parsec-cloud related issue](https://github.com/Scille/parsec-cloud/issues/1230#issue-645695975), One way to fix this, can be that winfspy catches this case, and throws STATUS_OBJECT_NAME_NOT_FOUND as before. This way, there won't be any impact in the parent Parsec code base.

**Comment by vxgmichel** [comment]
See my explanation here: https://github.com/Scille/parsec-cloud/issues/1230#issuecomment-651091027
