### ISSUE TITLE
Opening PDF Files with Adobe Reader DC fails

### ISSUE THREAD

**Issue by robert-boulanger** [Scille/winfspy#27]
Another issue  with common file formats.
Adobe Reader DC cannot open any PDF docuents stored in the provided memfs.
To reproduce, just copy any PDF document on the memfs.
Either by double clicking in Explorer on the document or via File Open Dialog, Adobe Reader reports the file can't be opened, Access denied.

To avoid this behaviour the following workaround helps: Disable "Run in App Container" in Adobe Acrobats  Settings. 
(Settings - Security (extended) - middle checkbox at the top )

Even this workaraound will help, it is not an option for many Users in secured environments or if the do not have this option due security policies in enterprises.

I started investigations in this topic to find out whats the difference of this setting  on FS level, but I still have no more information yet.

**Comment by vxgmichel** [comment]
Hi @robert-boulanger , 

This is a known issue with Acrobat Reader DC: https://github.com/billziss-gh/winfsp/issues/274

Note that it only happens for file systems mounted in a directory, it works fine with drives:
```shell
python -m winfspy.memfs X:
```
