### ISSUE TITLE
No NULL Bytes for filename sizes

### ISSUE THREAD

**Issue by kochelmonster** [Scille/winfspy#4]
Hi Emmanuel,
Is saw some of your recent code changes and there are still a bug in calculating filename sizes:

1. The filename size is calculated without a NULL byte. You can see this by
executing a os.listdir with python, all filenames have (incorrectly) that extra null byte.
2. encoding a name to utf16 just for getting its 2 byte unicode size is a little bit overkill.
len(file_name.encode("utf16")) is much slower then 2*len(file_name) and you do that pretty often
reading a large directory.

Best Regards
Michael

**Comment by touilleMan** [comment]
Hi Michael,

> The filename size is calculated without a NULL byte. You can see this by
executing a os.listdir with python, all filenames have (incorrectly) that extra null byte.

Not sure want you mean, can you elaborate ? (I find really strange that you get a null byte as part of a name of a file retourned by a `os.listdir` given windows explicitly [forbids null character in file name](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions)...)

Maybe you talk about [here](https://github.com/Scille/winfspy/blob/8ea5d2c4f510337ac527eaa8982c3e7c6f4e08c3/src/winfspy/operations.py#L599) where we receive an already allocated `FSP_FSCTL_DIR_INFO` but replace it size parameter by our own computation (I stopped this while reading your issue ^^).
I guess we should instead compare the given size field with our own computed size to make sure the buffer is big enough.

> encoding a name to utf16 just for getting its 2 byte unicode size is a little bit overkill.
len(file_name.encode("utf16")) is much slower then 2*len(file_name) and you do that pretty often
reading a large directory.

The trouble is utf16 (which is used by Windows for all unicode stuff) can encode certain characters with more than 2 bytes:
```python
>>> len("x".encode('utf-16le'))
2
>>> "x".encode('utf-16le')
b'x\x00'
>>> unicodedata.lookup("snake")
'🐍'
>>> len(unicodedata.lookup("snake").encode('utf-16le'))
4
>>> unicodedata.lookup("snake").encode('utf-16le')
b'=\xd8\r\xdc'
```

So for instance with a file named '🐍🐍🐍' we would endup with a 14 bytes string (3 snakes characters encoded each on 4 bytes plus a 2 bytes null character) which would cause a segfault if we allocate a buffer with the previous `2 * len(string) + 1 = 7` algo :'(

Obviously this is not optimized given we do 2 time the utf16 conversion (1 for getting the length plus one implicitly done by cffi when assigning the python str to the wchar_t* buffer)

**Comment by touilleMan** [comment]
acd4c45cbf66adda087833c03c46f1af285cf2ec should have improved things ;-)
